### ISSUE TITLE
Partition sizes on Vagrant boxes are smaller than on AMIs.

### ISSUE THREAD

**Issue by eseglem** [plus3it/spel#154]
### Expected behavior

I would expect the partition sizes on all builds to be the same in order to have identical environments for development / deployment.

### Actual behavior

The Vagrant partitions are significantly (about 50%) smaller than the AMI partitions, as listed below.

```
                Vagrant AMI
/               1.6G    3.9G
/boot           190M    453M
/home           380M    976M
/var            772M    2.0G
/var/log        772M    2.0G
/var/log/audit  3.4G    8.3G
```

This causes builds to fail on Vagrant because the `/` volume fills up when running `yum install`, where they would not fail on the AMI.

### Steps to reproduce behavior

Launch the Vagrant box and run `df -h` then launch an AMI and run `df -h` and compare the results.

### Suggestions for fix

Adjust the Vagrant box to meet the expected partition sizes.

**Comment by lorengordon** [comment]
In the vagrant boxes only 8GB is allocated of the 20GB disk, where on the AMIs the whole 20GB is allocated. I believe you should be able to extend the free space across whichever partition you need it.

**Comment by eseglem** [comment]
Right, we can expand the partitions, however that then requires changes to scripts to match them together. I would think the Vagrant boxes should be identical in partition size to the AMIs, so that there is no different to install scripts needed. What is the reason for the partitions being smaller in Vagrant than the AMI? If it is no possible to change it on the Vagrant box being provided, would you be able to provide a script / config to increase the sizes of them to match?

**Comment by lorengordon** [comment]
The creation of the vagrant boxes is far enough back in the memory of things that it's impossible to say what the original reasoning was for this configuration. All I remember is the vagrant boxes were a bit of an experiment, and I was trying to make the partition sizes proportional to those in the AMI. I do not remember why only 8GB was allocated in the first place. Probably some attempt (possibly mis-guided) to minimize the vagrant box size? Eh.

There hasn't really been a lot of demand for the vagrant boxes, and we ourselves have very little expertise with vagrant... Which goes to mean that we do not have strong opinions here and our time priorities are elsewhere. If you are partial to the vagrant boxes and have stronger opinions about what they should be, this is an open source project and community contributions are highly welcome (via pull requests)...

**Comment by eseglem** [comment]
Yeah, we are looking into it, and will see what we can do. Looks like it might be a simple change in https://github.com/plus3it/spel/blob/develop/spel/kickstarts/ks.centos6.minimal.cfg to up the sizes to approximately equivalent.
