### ISSUE TITLE
No username is documented for the published AMIs

### ISSUE THREAD

**Issue by HewittJC** [plus3it/spel#225]
### Expected behavior

Username Displayed in documentation or AMI listing on AWS

### Actual behavior

No username is documented

### Steps to reproduce behavior

Start Machine

### Context/Specifications

Couldn't find any username for any of the AMI's. I specifically am using the latest CentOS7 version in us-gov-west.

I had to look at the system logs in the AWS web console to find that the username was `maintuser`

### Suggestions for fix

Please include default username somewhere for people to see.

**Comment by lorengordon** [comment]
@HewittJC Good point. Addressing in #227.
