### ISSUE TITLE
EXT4 vs XFS for most partitions

### ISSUE THREAD

**Issue by creplogle** [plus3it/spel#257]
In the EL7 images the root, var|var/log|var/log/audit partitions are all EXT4. That is the partition format used for EL6. I am trying to increase the size of the /, /var, /var/log, /var/log/audit, and /home filesystems by increasing the size of the EBS volume associated with VolGroup00. Using fdisk to resize the xvda2 partition works fine, as does pvresize /dev/xvda2. When I execute a vgextend VolGroup00 /dev/xvda2 the command is successful and the volume group is the new size of the EBS volume. I then extend each logical volume using something like "lvextend -L 10GB /dev/VolGroup00/homeVol" for each logical volume. Running lvs shows that each volume is now the size I would like. But the actual filesystem has not increased. For XFS file systems I can run xfs_growfs /home and it will increase the size of the /home file system. I can use resize2fs but that's an EL6-based command as is the EXT4 partition type. Please make all partitions XFS.

**Comment by ferricoxide** [comment]
1) Use of the `-r` flag is recommended when executing `lvextend`: this will cause the LVM utilities to attempt to re-size the filesystem to whatever the new volume geometry is.
2) `resize2fs` is a _EFS_ command, not an "EL6-based command" 

Please read the [Larger Than Default Root EBS](/plus3it/spel/blob/develop/docs/LargerThanDefaultRootEBS_EL7.md) (for EL7) sub-document of this project's [FAQ](/plus3it/spel/blob/develop/docs/FAQ.md)
