### ISSUE TITLE
Boot Partition

### ISSUE THREAD

**Issue by pm9448** [plus3it/spel#300]
### Expected behavior

Redhat recommended 1GB

### Actual behavior

190M

### Steps to reproduce behavior

Update kernel.

### Context/Specifications

Things like:
- Template name
- AWS Component
- OS/AMI information

The simple update 'yum -y update' fails because there is not enough partition size.

### Suggestions for fix

Increase default partition to 1GB or make it EXT4

### Relevant references
- links to "best practices" or other guide(s)
- ...
- ...

**Comment by ferricoxide** [comment]
OS (CentOS/RHEL) and version (6/7), please?

As it stands, the [underlying automation](https://github.com/plus3it/AMIgen7/blob/master/DiskSetup.sh#L8) creates `/boot` as a 500MiB partition. On a freshly-launched (both CentOS and RHEL 7) instance, this looks like:

~~~
$ df -PH /boot
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda1      475M  129M  318M  29% /boot
$ grep /boot /proc/mounts
/dev/xvda1 /boot ext4 rw,seclabel,relatime,data=ordered 0 0
~~~

This has typically been sufficient for users of the AMIs that we produce.

A couple of notes:
1. As shown above, the `/boot` partition is already of type `ext4`
1. Typically, the only thing contributing content to the `/boot` partiton are the `kernel`, `logos` and `grub2-pc` RPMs.
1. Both the `logos` and `grub2-pc` RPMs are replacement-type updates. These updates are fairly rare and the size deltas are generally small.
1. The `kernel` RPMs are typically in the 60-75MiB range. Assuming no effort to remove old kernels, that typically allows space for `<current> + 4`.
1. `<current> + 4` is the default value set in `/etc/yum.conf`

If your specific use-case is causing space to be problematic, you can afford yourself some relief by either periodically executing something like `package-cleanup --oldkernels --count=2` or changing the default `installonly_limit=5` to a lower value in the  `/etc/yum.conf` file. In either case, this should result in only the current kernel RPM's (up to whatever count you set's) contents being present in `/boot`.

**Comment by ferricoxide** [comment]
@pm9448 did you have a chance to review my comments? If I don't see any further input from which to determine a suitable urgency/work-priority, I'm going to have to close this with a `WONTFIX` status. That will likely happen CoB final work-day of this month.

**Comment by pm9448** [comment]
My apologies for the delay in my response.  My issue with the distribution stems from the Vagrant version.  When downloaded and installed through Vagrant, I discovered that the boot partition is less than 200mb.

Is there a way to download an ISO of this build?

**Comment by confusdcodr** [comment]
@pm9448 - we will be increasing the size of the boot partition on the vagrant box to 512MiB with the next version

**Comment by lorengordon** [comment]
Closed by https://github.com/plus3it/spel/pull/305
