### ISSUE TITLE
first try to build centos7 box on local

### ISSUE THREAD

**Issue by thatsk** [plus3it/spel#353]
packer build     -var 'vagrantcloud_username=test'     -var 'spel_identifier=unique-project-id'     -var 'spel_version=0.0.1'     spel/minimal-linux.json
minimal-centos-7-azure-image output will be in this color.
minimal-centos-7-azure-vhd output will be in this color.
minimal-centos-7-hvm output will be in this color.
minimal-centos-7-virtualbox output will be in this color.
minimal-rhel-7-hvm output will be in this color.

5 error(s) occurred:

* A capture_name_prefix or managed_image_resource_group_name must be specified
* An image_publisher must be specified
* An image_offer must be specified
* An image_sku must be specified
* Specify either a location to create the resource group in or an existing build_resource_group_name, but not both.

**Comment by thatsk** [comment]
what is steps to build vagrant local machine try to test all things are working and as expected

**Comment by ferricoxide** [comment]
Sorry, just now noticed this. Are you still having issues, or did you eventually start invoking with _just_ the Vagrant-builder (``)?

**Comment by ferricoxide** [comment]
No response from issue-originator in rolling-up on three months. Assuming this is no longer an issue.
