### ISSUE TITLE
RHEL/CentOS 8 Supoport

### ISSUE THREAD

**Issue by jmoyer** [plus3it/spel#365]
Are there plans to publish a CentOS/RHEL 8 version of SPEL?  I see the old ticket below, however, now there is CentOS 8 and EPEL 8 support.   

https://github.com/plus3it/spel/issues/322

Thanks, 

John

**Comment by ferricoxide** [comment]
As noted in the relevant [FAQ entry](https://github.com/plus3it/AMIgen8):

> _Initial functionality for any given ELx build orchestrated by spel starts with an AMIgen project. Functionality for EL8 will be trackable within the AMIgen8 project._

Until you see something _there_, you are unlikely to see anything in this project.
