### ISSUE TITLE
Build fails with can't create providesname index

### ISSUE THREAD

**Issue by damonsmith** [plus3it/spel#375]
I'm trying to use a RHEL-7.7 image in AWS as the source AMI - ami-0f1ef883e90ca71c0 - in ap-southeast-2 region. It fails with: TypeError: Can not create providesname index: database or disk is full.

A larger bit of stack trace:
```
minimal-rhel-7-hvm: + yum '--disablerepo=*' --enablerepo=rhui-REGION-client-config-server-7,rhui-REGION-rhel-server-releases,rhui-REGION-rhel-server-rh-common,rhui-REGION-rhel-server-optional,rhui-REGION-rhel-server-extras,rhui-client-config-server-7,rhel-7-server-rhui-rpms,rhel-7-server-rhui-rh-common-rpms,rhel-7-server-rhui-optional-rpms,rhel-7-server-rhui-extras-rpms,rhui-rhel-7-server-rhui-rpms,rhui-rhel-7-server-rhui-rh-common-rpms,rhui-rhel-7-server-rhui-optional-rpms,rhui-rhel-7-server-rhui-extras-rpms,epel --installroot=/mnt/ec2-root -y reinstall redhat-release-server epel-release rh-amazon-rhui-client yum-utils
    minimal-rhel-7-hvm: Loaded plugins: amazon-id, search-disabled-repos
    minimal-rhel-7-hvm: rhel-7-server-rhui-extras-rpms                                        1229/1229
    minimal-rhel-7-hvm: rhel-7-server-rhui-optional-rpms                                    19636/19636
    minimal-rhel-7-hvm: rhel-7-server-rhui-rh-common-rpms                                       239/239
    minimal-rhel-7-hvm: rhel-7-server-rhui-rpms                                             27002/27002
    minimal-rhel-7-hvm: Traceback (most recent call last):
    minimal-rhel-7-hvm:   File "/bin/yum", line 29, in <module>
    minimal-rhel-7-hvm:     yummain.user_main(sys.argv[1:], exit_code=True)
    minimal-rhel-7-hvm:   File "/usr/share/yum-cli/yummain.py", line 375, in user_main
    minimal-rhel-7-hvm:     errcode = main(args)
    minimal-rhel-7-hvm:   File "/usr/share/yum-cli/yummain.py", line 184, in main
    minimal-rhel-7-hvm:     result, resultmsgs = base.doCommands()
    minimal-rhel-7-hvm:   File "/usr/share/yum-cli/cli.py", line 585, in doCommands
    minimal-rhel-7-hvm:     return self.yum_cli_commands[self.basecmd].doCommand(self, self.basecmd, self.extcmds)
    minimal-rhel-7-hvm:   File "/usr/share/yum-cli/yumcommands.py", line 2575, in doCommand
    minimal-rhel-7-hvm:     return base.reinstallPkgs(extcmds)
    minimal-rhel-7-hvm:   File "/usr/share/yum-cli/cli.py", line 1343, in reinstallPkgs
    minimal-rhel-7-hvm:     txmbrs = self.reinstall(pattern=arg)
    minimal-rhel-7-hvm:   File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 5737, in reinstall
    minimal-rhel-7-hvm:     repoid=kwargs.get('repoid_install'))
    minimal-rhel-7-hvm:   File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 4872, in install
    minimal-rhel-7-hvm:     pkgs = self.pkgSack.searchNevra(name=nevra_dict['name'],
    minimal-rhel-7-hvm:   File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 1075, in <lambda>
    minimal-rhel-7-hvm:     pkgSack = property(fget=lambda self: self._getSacks(),
    minimal-rhel-7-hvm:   File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 778, in _getSacks
    minimal-rhel-7-hvm:     self.repos.populateSack(which=repos)
    minimal-rhel-7-hvm:   File "/usr/lib/python2.7/site-packages/yum/repos.py", line 386, in populateSack
    minimal-rhel-7-hvm:     sack.populate(repo, mdtype, callback, cacheonly)
    minimal-rhel-7-hvm:   File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 263, in populate
    minimal-rhel-7-hvm:     dobj = repo_cache_function(xml, csum)
    minimal-rhel-7-hvm:   File "/usr/lib64/python2.7/site-packages/sqlitecachec.py", line 46, in getPrimary
    minimal-rhel-7-hvm:     self.repoid))
    minimal-rhel-7-hvm: TypeError: Can not create providesname index: database or disk is full
==> minimal-rhel-7-hvm: Provisioning step had errors: Running the cleanup provisioner, if present...
```
Am I using a bad AMI as the source? I can build the latest us-east-1 RHEL-7.5 image fine, I tried increasing the size of the volume groups in the new FS and added fdisk and df calls and I can see they've all got plenty of spare space.

### Context/Specifications

Things like:
- Template name
- AWS Component
- OS/AMI information

### Relevant references
- links to "best practices" or other guide(s)
- ...
- ...

**Comment by ferricoxide** [comment]
First Google his is a Red Hat [article](https://access.redhat.com/solutions/3602431). Dunno if this applies. We don't generally use or otherwise test with source-AMIs outside of the CONUS regions. 

We have yet to see this on our monthly builds or CI tests. Our CI system currently starts with [ami-029c0fbe456d58bd1](https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#Images:visibility=public-images;imageId=ami-029c0fbe456d58bd1;sort=desc:creationDate) which _is_ an RHEL-created, RHEL 7.7 AMI.

If you have the ability to re-run what you're doing in us-east-1 to see if you get different results, I'd suggest that. Otherwise, I don't really have enough information to help you.

**Comment by lorengordon** [comment]
One idea I had, as a workaround for whatever is going on, was to build the AMI in a region where you do have it working, using `aws_region`, but then have packer copy the AMI to regions where you need to use it, using `ami_regions`.

That will actually leave the AMI in the build region also. But if the general approach works for you, and you also want to remove the AMI in the build region, we can expose [`skip_save_build_region`](https://packer.io/docs/builders/amazon-ebs.html#skip_save_build_region) so you can have packer automatically clean up the AMI.

**Comment by damonsmith** [comment]
Thanks for that, that is very handy to know. After much confusion it turns out I was using the non GA release of RHEL and once I changed it to GA it worked fine. My bad, sorry!
