### ISSUE TITLE
Subscriptions not working even with billingProducts set

### ISSUE THREAD

**Issue by damonsmith** [plus3it/spel#379]
Hi sorry to bother again, so instances are not registered to an entitlement server, is that by design? What's the point of going through all the hassle of maintaining the billingProducts if the instance ends up not being registered anyway?

### Expected behavior
yum update behaves normally

### Actual behavior
yum reports that the system is not registered with an entitlement server

### Steps to reproduce behavior
[maintuser@ip-10-210-137-160 ~]$ curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | grep -i billingProducts
  "billingProducts" : [ "bp-6fa54006" ],
[maintuser@ip-10-210-137-160 ~]$ sudo yum update
Loaded plugins: amazon-id, product-id, search-disabled-repos, subscription-manager
This system is not registered with an entitlement server. You can use subscription-manager to register.

### Context/Specifications

Things like:
- Template name
- AWS Component
- OS/AMI information

### Relevant references
- links to "best practices" or other guide(s)
- ...
- ...

**Comment by damonsmith** [comment]
Oh I just realised that this is because vanilla Red Hat images have subscription manager disabled in /etc/yum/pluginconf.d/subscription-manager.conf, but it gets turned back on again in the spel build. Easy fix for me.

**Comment by lorengordon** [comment]
Interesting. We just reinstall the RHEL rpms into the chroot. Whichever package manages that file must have it on by default, with RedHat having some post-install process to disable it.

We've always just ignored that message. From what I gather, the message is really only saying that the system is not associated to RHN, which is correct. EC2 instances do not need to be associated to RHN to get updates. Access to updates is provided by RHUI and is governed by the presence of the billing product code.
