### ISSUE TITLE
[Documentation Update] FAQ Needs Nitro Examples

### ISSUE THREAD

**Issue by ferricoxide** [plus3it/spel#402]
**Problem Description:**
Currently, the FAQ's [Larger-Than-Default Root EBS](https://github.com/plus3it/spel/blob/master/docs/LargerThanDefaultRootEBS_EL7.md) content only provides guidance/examples for use with pre-Nitro AWS instance-types.

**Fix:**
Update to add Nitro examples.

**Comment by lorengordon** [comment]
Lucky us, cloud-init now creates the symlink for the `/dev/xvdX` names :D
