### ISSUE TITLE
CentOS 8 AMIs now available

### ISSUE THREAD

**Issue by AfroThundr3007730** [plus3it/spel#407]
The [bug report](https://bugs.centos.org/view.php?id=16614) closed this morning with a note that the AMIs for CentOS 8 have been published. The new AMI IDs can be found on the [wiki page](https://wiki.centos.org/Cloud/AWS#Images).

**Comment by ferricoxide** [comment]
Safe to assume you're posting this to poke us to create some EL8 AMIs? If so, we _have_ published beta AMIs for both RHEL8 and a CentOS8 .

||us-east-1|us-east-2|us-west-1|us-west-2|
|------------|------------|------------|------------|------------|
| RHEL |ami-00f819a269842b255|ami-0aefdbfae175d477e|ami-0908959d263dd85cf|ami-04afea0f9384df524|
| CentOS |ami-037e7adfb7feb6a19|ami-01d31e4a64092cf40|ami-0d5e3c41f8175199b|ami-0b33c228c220f6e90|

However, it should be noted that they are _**BETA**_ (tried to make it obvious with their AMI names). We're currently working on finishing up our CI tooling to do validation of produced AMIs. 

If you want to give those beta AMIs some poking to help us find things to fix (and capture in our CI-testing), that'd be awesome.

For details on the build-contents, pleas see the [AMIgen8](/plus3it/AMIgen8) project's code.
