### ISSUE TITLE
AWS data unable to use s3 commands without setting var

### ISSUE THREAD

**Issue by Rinzler081** [plus3it/spel#430]
All commands including s3 work fine as either ec2-user or root.

My issue: For some reason only when I launch a server, in the user data I'm doing just a simple aws s3 cp command I get the ssl_verify_certificate error.

Understand userdata runs as root. I've reinstalled the tools still no same issue. Any help would be appreciated

Running Centos 7.9

### Expected behavior
s3 commands to work at user data
with out having to set the aws_ca_bundle variable

### Actual behavior
ssl_verify error
but when logging in afterwards no issue running commands

### Context/Specifications

Things like:
- Template name
- AWS Component
- OS/AMI information

### Relevant references
- links to "best practices" or other guide(s)
- ...
- ...

**Comment by lorengordon** [comment]
Can you provide a reproduction case, per the issue template? Preferably exact userdata contents and the `aws ec2 run-instances` command?

**Comment by ferricoxide** [comment]
This ticket is rolling up on a month old with no activitity. Without further response from the ticket-originator (@Rinzler081) this ticket will be closed on Friday (2021/01/08)

**Comment by lorengordon** [comment]
Closing due to lack of response.
