### ISSUE TITLE
aws cli does not run as root user

### ISSUE THREAD

**Issue by madelponte** [plus3it/spel#435]
when awscli v2 is installed, it gets put in to /usr/local/bin which the root user does not have in it's $PATH
as a result the root user is not able to run aws comands without modifying the path

### Steps to reproduce behavior

1. build spel with awscliv2
2. log into the root user and run aws

### Suggestions for fix

Either add /usr/local/bin to root $PATH or move aws to a different directory that is in the root's $PATH

**Comment by lorengordon** [comment]
This is the install location that the Amazon documentation uses also. Managing the PATH for the root user feels like it should be out of the scope of this project.

aws v1: https://docs.aws.amazon.com/cli/latest/userguide/install-linux.html#install-linux-bundled-sudo
aws v2: https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-linux.html#cliv2-linux-install

**Comment by ferricoxide** [comment]
Without further input from @madelponte , this ticket will be closed on 2020/01/18

**Comment by lorengordon** [comment]
Closing due to lack of response.
