### ISSUE TITLE
Vagrant box add

### ISSUE THREAD

**Issue by alwinkpc** [plus3it/spel#51]
Greetings,

Testing your box I got the following

     $ vagrant box add plus3it/spel-minimal-centos-6.9
    ==> box: Loading metadata for box 'plus3it/spel-minimal-centos-6.9'
        box: URL: https://atlas.hashicorp.com/plus3it/spel-minimal-centos-6.9
    ==> box: Adding box 'plus3it/spel-minimal-centos-6.9' (v2017.05.1) for provider: virtualbox
        box: Downloading: https://atlas.hashicorp.com/plus3it/boxes/spel-minimal-centos-6.9/versions/2017.05.1/providers/virtualbox.box
    The "metadata.json" file for the box 'plus3it/spel-minimal-centos-6.9' was not found.
    Boxes require this file in order for Vagrant to determine the
    provider it was made for. If you made the box, please add a
    "metadata.json" file to it. If someone else made the box, please
    notify the box creator that the box is corrupt. Documentation for
    box file format can be found at the URL below:

    https://www.vagrantup.com/docs/boxes/format.html

**Comment by lorengordon** [comment]
That's quite odd. The .box that was pushed to atlas definitely has the metadata.json file, but the .box pulled from atlas does not. Will need to investigate more...

**Comment by lorengordon** [comment]
Shoot, I see what I did. I'll put together a patch and test it later today.

**Comment by alwinkpc** [comment]
Thank you. This was fast. Happy to help!

**Comment by lorengordon** [comment]
@alwinkpc alright, pushed a new version that looks correct to me. 2017.5.1-1. please give it a shot and let us know how it goes.

**Comment by alwinkpc** [comment]
I tried last night with same results. Finally I used `hashicorp/precise64`

**Comment by lorengordon** [comment]
I can only imagine there is some environmental issue, or cache, in the way. If you download the two boxes and extract them, you can see that the contents of 2017.15.1 are bad, and 2017.15.1-1 are good.

- https://atlas.hashicorp.com/plus3it/boxes/spel-minimal-centos-6.9/versions/2017.05.1/providers/virtualbox.box
- https://atlas.hashicorp.com/plus3it/boxes/spel-minimal-centos-6.9/versions/2017.05.1-1/providers/virtualbox.box
