### ISSUE TITLE
[Enhancement] Increase the Root Partition-Size in the Produced-AMIs

### ISSUE THREAD

**Issue by ferricoxide** [plus3it/spel#595]
### Problem Description

EL 8.7+ distros have gotten fat. Installation of hardening tools and other packages onto a freshly-deployed EC2 is resulting in out-of-space errors on the `/` filesystem. For example:

~~~
      Error: Transaction test error:
        installing package scap-security-guide-0.1.66-2.el8.noarch needs 74MB on the / filesystem

      Error Summary
      -------------
      Disk Requirements:
         At least 74MB more space needed on the / filesystem.
~~~

While this can be prevented at launch-time by including additional provisioning-logic, it would be easier for users of the EL8 AMIs to not have to account for this gap.

### Expected behavior

The `/` filesystem should have more free-space on it at first-launch.

### Actual behavior

Provisioning-time tasks are failing due to insufficient space on the `/` filesystem

### Steps to reproduce behavior

Launch new EC2 from published AMIs and attempt to install new software of arbitrary size that requires space in the `/` filesystem.

### Context/Specifications

Things like:
- Template name
- AWS Component
- OS/AMI information

### Suggestions for fix

1. Increase root EBS volume-size
2. Increase root LVM volume-size
3. Increae `/` filesystem size

Increasing the above sizes by 5GiB should provide sufficient breathing room for most newly-launched EC2s

**Comment by lorengordon** [comment]
Closed by https://github.com/plus3it/spel/pull/603 and https://github.com/plus3it/spel/pull/596
