### ISSUE TITLE
New AWS account source

### ISSUE THREAD

**Issue by brandonrace** [plus3it/spel#627]
### Expected behavior
SPEL images were always being shared from an AWS account with the account id 039368651566 

### Actual behavior
SPEL images are now coming being shared from an AWS account with the account id 216406534498 as of spel-minimal-rhel-7-hvm-2023.08.1.x86_64-gp2

### Context/Specifications
I just wanted to verify that these were still Plus3IT SPEL images and that the account id change was intentional

### Relevant references
- links to "best practices" or other guide(s)
- ...
- ...

**Comment by lorengordon** [comment]
Yes, that is intentional. Apologies for the confusion. We'll be updating the README with the correct links, and some discussion.

**Comment by brandonrace** [comment]
Thanks for the quick response!

**Comment by brandonrace** [comment]
Sounds good, thanks!

**Comment by lorengordon** [comment]
@brandonrace closing the loop, we just updated the readme with a new table that lists the account ids and the effective release. See:

* https://github.com/plus3it/spel#official-aws-owner-account-ids-for-images
* https://github.com/plus3it/spel/pull/628
