### ISSUE TITLE
requesting an appropriate FAQ entry

### ISSUE THREAD

**Issue by hellzrellz** [plus3it/spel#655]
I'm inquiring if there will be a spel released image of AlmaLinux 8 in govcloud regions?

**Comment by lorengordon** [comment]
We don't currently support building AlmaLinux 8 images at all. Currently the supported el8 OSes include: Red Hat 8, CentOS Stream 8, and Oracle Linux 8.

We've done a little work extending support to AlmaLinux and Rocky Linux, and maybe one more I'm forgetting, but it's not currently published or available. When complete, then yes, images for all OSes will be published to both commercial and govcloud partitions.

**Comment by ferricoxide** [comment]
The automation has been tested to produce both Alma and Rocky distros. However, as Loren notes, we haven't published any "final" AMIs for either distro.

**Comment by ferricoxide** [comment]
Closing due to lack of further response from reporter.
