### ISSUE TITLE
Move the "enable amazon-ssm-agent" to be set only if SSM Agent is desired to be installed.

### ISSUE THREAD

**Issue by platymatt** [plus3it/spel#701]
Requesting moving "enable amazon-ssm-agent" process so it's only set if the SSM Agent is installed.

This code below always adds the `-t amazon-ssm-agent` to the running of AWSUtils.sh even if one opts out of installing the SSM Agent by not providing the URL in the variable `amigen8_extra_rpms`.

https://github.com/plus3it/spel/blob/87a1b138a15ade1808f65206dc5fd3bc0b689f4a/spel/scripts/amigen8-build.sh#L295

It looks like `AMIGENSSMAGENT="${SPEL_AMIGENSSMAGENT}"` is not configurable or passed in from the minimal-linux.pkr.hcl template. So maybe this should change as well to make it an optionable install from packer variables within the minimal-linux.pkr.hcl template?

**Comment by lorengordon** [comment]
Hmm. We defaulted to always including the ssm-agent because it is also included in Amazon Linux, and that parity is a design goal of the project. I see the point though. Perhaps we could expose another env, `AMIGENSERVICES`, and construct the string from that.

Not so much a priority for us, but if you want to submit a PR, we can happily review it.

**Comment by platymatt** [comment]
Thank you for clarifying as I wasn’t aware of the parity goal with Amazon Linux and thought  the goal was STIG partitioning. My use case is I am trying to deploy this in an isolated environment and the SSM and AWS CLI are being provided somewhat differently that come with their own issues so if I could avoid them it would make things easier to install them separately.

I was initially trying to not include aws cli and SSM, but that’s not an option with either. I figured if I didn’t provide the SSM url in the extra_rpms then it would not be an issue, but one has to have it installed so it can be enabled.

I should be able to make the SSM install work if I prep the base ami properly.  Maybe I can front load it instead and pass the enablement check?

**Comment by platymatt** [comment]
Currently I can pull the packages I need from hosted URLs. I just have to add a certain AWS cert bundle to the trust store to get the `rpm -q` check to pass on the SSM.rpm install. I figured I could opt out of SSM, but that’s not the case here which is ok.

**Comment by lorengordon** [comment]
Ahh, ok. So yeah. For isolated environments, one of the ways we do things like that is package up those requirements in their own RPM, which we then host, and then include the URL to the RPM in the `extra_rpms` input...

**Comment by platymatt** [comment]
So for this issue I'm ok with closing it. I understand the Amazon Linux feature parity goal here and wasn't aware of it before. Thank you for explaining everything. I continue to struggle with offline environment installs, but I think I'll get past it soon.

**Comment by lorengordon** [comment]
Thanks @platymatt. I'll go ahead and close as Not Planned, but if you change your mind about implementing the feature, feel free to reopen the issue and submit a pull request with the change.

**Comment by platymatt** [comment]
Thanks. I still like the "feature" and being able to pair back that piece would be nice and helpful. So by Default it would be parity with Amazon Linux, but one can do this to skip SSM or other AWS pieces.

I'm still having the same issue with the `rpm -q` command. So I have to skip installing it most likely within the spel image process.

**Comment by platymatt** [comment]
If i follow this same process with the same base RHEL AMI I'm using with the spel pkr.hcl outside of the packer process.
1. `yum install -y <https://ssm-url.com>`
2. `rpm -q <https://ssm-url.com>`
I get no errors.

But if I use the same SSM URL within the packer build process I get a "self signed cert" error on the `rpm -q` step.

**Comment by platymatt** [comment]
I feel silly as I was installing the session-manager-plugin.rpm instead of the aws-ssm-agent.rpm. I didn't realize this until I made some manual edits to use the AWSUtils.sh `-s` flag and it error'd during enabling the service.

@lorengordon is the contribution guidelines to make a PR to this repo correct? I'm using this https://github.com/plus3it/spel/blob/master/docs/CONTRIBUTING.md as a guide.

Do I need to test the solution myself or is it able to be tested within the existing pipelines of this project?

**Comment by lorengordon** [comment]
> @lorengordon is the contribution guidelines to make a PR to this repo correct? I'm using this [`master`/docs/CONTRIBUTING.md](https://github.com/plus3it/spel/blob/master/docs/CONTRIBUTING.md?rgh-link-date=2024-08-27T17%3A27%3A35Z) as a guide.

Reasonably accurate, but not critical. If you one the PR and there are issues, we'll address it in review. And as long as you leave the box checked to allow maintainers to edit the PR, then I'll probably just pull it and address anything related to a failing pipeline.

> Do I need to test the solution myself or is it able to be tested within the existing pipelines of this project?

I mean, a little of both... I'd rather expect you to build your image using your branch, to confirm the changes work for your use case. But I suppose that's up to you. Certainly we'll also exercise the pipelines linked to the project to ensure they remain functional.

**Comment by platymatt** [comment]
Thank you for your response. I will reopen this when I am ready.
