### ISSUE TITLE
Redhat Hourly License

### ISSUE THREAD

**Issue by mgresko** [plus3it/spel#79]
I am using packer and specifying the SPEL Redhat 7.3 hvm AMI as the source.  I want to run a bunch of ansible against it to STIG harden and then use the new AMI for all my ec2 instances.  The problem is when I launch the instance from AMI the license hasn't carried over.  Specifically rhui does not work.  I am using ebs-builder.  I realize this is not a problem with spel just looking for a little help.  :)

As another point of reference, I also tried modifying the spel minimal-linux.json with the ansible hardening and when it runs it always says /dev/xvda is busy and can't open....  Not sure what is going on there.  Any direction on best way to inject hardening process would be appreciated.

```
    minimal-rhel-7.4-hvm: + break
    minimal-rhel-7.4-hvm: + [[ -z xxx ]]
    minimal-rhel-7.4-hvm: + [[ ! -z '' ]]
    minimal-rhel-7.4-hvm: + [[ -z '' ]]
    minimal-rhel-7.4-hvm: + [[ ! -z xxx ]]
    minimal-rhel-7.4-hvm: + CarveLVM
    minimal-rhel-7.4-hvm: + ROOTVOL=(rootVol 4g)
    minimal-rhel-7.4-hvm: + local ROOTVOL
    minimal-rhel-7.4-hvm: + SWAPVOL=(swapVol 2g)
    minimal-rhel-7.4-hvm: + local SWAPVOL
    minimal-rhel-7.4-hvm: + HOMEVOL=(homeVol 1g)
    minimal-rhel-7.4-hvm: + local HOMEVOL
    minimal-rhel-7.4-hvm: + VARVOL=(varVol 2g)
    minimal-rhel-7.4-hvm: + local VARVOL
    minimal-rhel-7.4-hvm: + LOGVOL=(logVol 2g)
    minimal-rhel-7.4-hvm: + local LOGVOL
    minimal-rhel-7.4-hvm: + AUDVOL=(auditVol 100%FREE)
    minimal-rhel-7.4-hvm: + local AUDVOL
    minimal-rhel-7.4-hvm: + dd if=/dev/zero of=/dev/xvda bs=512 count=1000
    minimal-rhel-7.4-hvm: + parted -s /dev/xvda -- mklabel msdos mkpart primary ext4 2048s 500m mkpart primary ext4 500m 100% set 2 lvm
    minimal-rhel-7.4-hvm: Error: Partition(s) 2 on /dev/xvda have been written, but we have been unable to inform the kernel of the change, probably because it/they are in use.  As a result, the old partition(s) will remain in use.  You should reboot now before making further changes.
    minimal-rhel-7.4-hvm: + systemctl stop boot.mount
    minimal-rhel-7.4-hvm: Failed to stop boot.mount: Unit boot.mount not loaded.
    minimal-rhel-7.4-hvm: + vgcreate -y VolGroup00 /dev/xvda2
    minimal-rhel-7.4-hvm: Can't open /dev/xvda2 exclusively.  Mounted filesystem?
    minimal-rhel-7.4-hvm: + LogBrk 5 'VG creation failed. Aborting!'
    minimal-rhel-7.4-hvm: + echo 'VG creation failed. Aborting!'
    minimal-rhel-7.4-hvm: VG creation failed. Aborting!
    minimal-rhel-7.4-hvm: + exit 5
```

**Comment by lorengordon** [comment]
@mgresko For RHEL, the source AMI should be one of the Red Hat-published images. At the moment, the most current for RHEL7 is  ami-cdc999b6.

**Comment by mgresko** [comment]
@lorengordon sorry should be more clear...  I have attempted two scenarios:

1.  I have a packer .json in which I specify your spel image as source, run some ansible on it spits out new ami with ebs-builder.  This does not carry over the license.

2.  I clone spel, modify the minimal-linux.json to include the hardening ansible before it starts partitioning.  This fails with the /dev/xvda error above.

Scenario 1 seems like the easiest to me but I don't understand why the license doesn't carry over.

**Comment by lorengordon** [comment]
For **2.**, the way spel works is to pivot_root to tmpfs/RAM as it boots, and then it uses the root volume to perform a chroot install. This is necessary to inherit the Red Hat license. Going this route, I would expect you would need to apply your hardening into the **chroot volume** _after_ the bulk of spel completes but before the volume is unmounted. If you don't harden in the chroot, then you are only operating on the tmpfs root, which is discarded when the AMI is created. Right now, I'd insert your hardening [here](https://github.com/plus3it/spel/blob/develop/spel/scripts/amigen7-build.sh#L182). To support this use case more easily, we could move the unmount into the packer template. If you want to have a go at that, PR's are welcome!

For **1.**, I'm not too sure. If you start with a spel AMI, do some stuff, and then use the CreateImage API, it _should_ retain the license. That's basically why spel is what it is, with the pivot_root thing. Based on your description, I think that's what would happen with the ebs-builder, so not too sure why it wouldn't be working...

> Some Linux distributions, such as Red Hat Enterprise Linux (RHEL) and SUSE Linux Enterprise Server (SLES), use the EC2 billing product code associated with an AMI to verify the subscription status for package updates. Creating an AMI from an EBS snapshot does not maintain this billing code, and subsequent instances launched from such an AMI will not be able to connect to package update infrastructure. To create an AMI that must retain billing codes, see [CreateImage](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateImage.html).

From: http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RegisterImage.html

**Comment by mgresko** [comment]
@lorengordon thanks for the info... trying your first suggestion now.  👍

**Comment by lorengordon** [comment]
@mgresko cool, let us know how it goes!

**Comment by mgresko** [comment]
@lorengordon I think the spel image generated has not carried over the license that allows it to access RHUI subscription.

Example:  RHEL Instance
```[ec2-user@ip-xx-xx-xx-xx ~]$ sudo yum makecache
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
rhui-REGION-client-config-server-7                                                                                                                                                        | 2.9 kB  00:00:00
rhui-REGION-rhel-server-releases                                                                                                                                                          | 3.5 kB  00:00:00
rhui-REGION-rhel-server-rh-common                                                                                                                                                         | 3.8 kB  00:00:00
Metadata Cache Created```

SPEL Image: ami-09c84968 (govcloud)
```[maintuser@ip-xx-xx-xx-xx ~]$ sudo yum makecache
Checksum type 'md5' disabled
Loaded plugins: amazon-id, product-id, rhui-lb, search-disabled-repos, subscription-manager
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.```

I am assuming this has something to do with it being copied from a marketplace instance...   Note:  I can still install packages not sure if this message about subscription is red herring.  Any ideas?  Am I confused here?

**Comment by lorengordon** [comment]
Definitely a red herring. If you can install packages, the license is good. See the second to last message in this thread, https://forums.aws.amazon.com/thread.jspa?threadID=126117. Or google for that exact message.

**Comment by mgresko** [comment]
Ok.  So that message is a red herring.  And I have now realized that the STIG hardening I am applying is what is killing RHUI.  Sigh.  Have to figure that out.  Sorry for the confusion.  Really appreciate the help!

**Comment by lorengordon** [comment]
No problem! Good luck!
