### ISSUE TITLE
Create Centos 7 Virtualbox Builder

### ISSUE THREAD

**Issue by ttindell2** [plus3it/spel#87]
Currently for virtualbox, there is only a Centos 6.9 virtualbox builder for vagrant. Requesting the addition of Centos 7.4 virtualbox builder.

**Comment by lorengordon** [comment]
If you can get it working, pull requests are welcome. 😁

**Comment by lorengordon** [comment]
@ttindell2 If you're still wanting this, please give this a try: https://app.vagrantup.com/lorengordon/boxes/spel-minimal-centos-7

Once https://github.com/plus3it/spel/pull/196 is merged, the box will be available under plus3it/spel-minimal-centos-7 following the next spel release...
